import 'package:hive/hive.dart';
class DBService {
 DBService._(); static late Box _users,_products,_sales,_items,_cash,_areas,_moves,_config;
 static Future<void> init() async { _users=await Hive.openBox('users');_products=await Hive.openBox('products');_sales=await Hive.openBox('sales');_items=await Hive.openBox('sale_items');_cash=await Hive.openBox('cash_sessions');_areas=await Hive.openBox('areas');_moves=await Hive.openBox('movements');_config=await Hive.openBox('config'); if(_users.isEmpty) {for(final u in [{'user':'admin','pass':'1234','role':'admin'},{'user':'cajero','pass':'1234','role':'seller'}]) await _users.put(u['user'],u);} }
 static Map<String,dynamic> _m(dynamic x)=>x is Map?Map<String,dynamic>.from(x.map((k,v)=>MapEntry('$k',v))):{};
 static Future<Map<String,dynamic>?> login(String u,String p) async {final x=_m(_users.get(u));return x['pass']==p?x:null;}
 static Future<Map<String,dynamic>?> getUser(String u) async {final x=_m(_users.get(u));return x.isEmpty?null:x;}
 static Future<void> putConfig(String k,dynamic v) async=>_config.put(k,v); static Future<dynamic> getConfig(String k) async=>_config.get(k); static Future<void> deleteConfig(String k) async=>_config.delete(k);
 static String getAppMode()=>_config.get('app_mode',defaultValue:'demo').toString(); static Future<void> setAppMode(String m) async=>putConfig('app_mode',m);
 static Future<List<Map<String,dynamic>>> getUsers() async=>_users.values.map(_m).toList(); static Future<void> upsertUser(Map<String,dynamic> u) async=>_users.put(u['user'],u); static Future<void> deleteUser(String u) async=>_users.delete(u);
 static Future<List<Map<String,dynamic>>> getProducts() async=>_products.toMap().entries.map((e){final x=_m(e.value);x['id']=e.key;x['stock']=int.tryParse('${x['stock']}')??0;return x;}).toList();
 static Future<void> insertProduct(Map<String,dynamic> p) async=>_products.put(_products.length,p); static Future<void> updateProduct(int id,Map<String,dynamic> p) async=>_products.put(id,{..._m(_products.get(id)),...p}); static Future<void> upsertProduct(Map<String,dynamic> p) async=>insertProduct(p); static Future<void> addStock(int id,int q) async {final p=_m(_products.get(id));p['stock']=(int.tryParse('${p['stock']}')??0)+q;await _products.put(id,p);} static Future<void> removeStock(int id,int q) async {final p=_m(_products.get(id));p['stock']=((int.tryParse('${p['stock']}')??0)-q).clamp(0,999999);await _products.put(id,p);}
 static Future<int> createSale(double total,String method,String user,{int? sessionId,List<Map<String,dynamic>>? payments}) async {final id=_sales.length;await _sales.put(id,{'id':id,'total':total,'method':method,'user':user,'payments':payments??[],'session_id':sessionId,'date':DateTime.now().toIso8601String()});return id;}
 static Future<void> insertSaleItem(Map<String,dynamic> x) async=>_items.put(_items.length,x); static Future<List<Map<String,dynamic>>> getSaleItems() async=>_items.values.map(_m).toList(); static Future<List<Map<String,dynamic>>> getSalesOfDay() async=>_sales.values.map(_m).toList();
 static Future<List<Map<String,dynamic>>> getMovementsOfDay() async=>_moves.values.map(_m).toList(); static Future<List<Map<String,dynamic>>> getAreas() async=>_areas.values.map(_m).toList();
 static Future<void> createMovement({required int productIndex,required int fromAreaId,required int toAreaId,required int qty,required String fromUser,required String toUser,required bool confirmedBySeller,String type='transfer',String? productName,String? note}) async=>_moves.put(_moves.length,{'product_index':productIndex,'from_area':fromAreaId,'to_area':toAreaId,'qty':qty,'from_user':fromUser,'to_user':toUser,'confirmed_by_seller':confirmedBySeller,'type':type,'product_name':productName??'','note':note??'','date':DateTime.now().toIso8601String()});
 static Future<int> openCashSession(double fund) async {final id=_cash.length;await _cash.put(id,{'id':id,'fund':fund,'open':DateTime.now().toIso8601String(),'close':null});return id;} static Future<Map<String,dynamic>?> getOpenCash() async {for(final x in _cash.values){final m=_m(x);if(m['close']==null)return m;}return null;} static Future<int> openCash(double f)=>openCashSession(f); static Future<List<Map<String,dynamic>>> getCashSessions() async=>_cash.values.map(_m).toList();
 static Future<void> closeCash(int id,double finalCash,double expectedCash) async=>closeCashSession(id,finalCash:finalCash,expectedCash:expectedCash); static Future<void> closeCashSession(int id,{double? finalCash,double? expectedCash,Map<String,dynamic>? productsStart,Map<String,dynamic>? productsEnd,Map<String,int>? cashCount,Map<String,dynamic>? transferCount,double? fund}) async {final m=_m(_cash.get(id));m['close']=DateTime.now().toIso8601String();m['final_cash']=finalCash;m['expected_cash']=expectedCash;await _cash.put(id,m);}
 static Future<Map<String,double>> getSessionPaymentSummary(int id) async=>{'total':0,'ventas':0,'efectivo':0,'transferencia':0,'tarjeta':0}; static Future<Map<String,int>> getProductSalesQtyOfDay() async=>{}; static Future<Map<String,dynamic>> getProductsStockMapStart() async=>{for(final p in await getProducts())'${p['name']}':p['stock']}; static Future<void> recordProductEntry({required String productName,required int qty,String user='admin',String note=''}) async {final p=(await getProducts()).firstWhere((x)=>x['name']==productName,orElse:()=>{});if(p.isEmpty) await insertProduct({'name':productName,'stock':qty,'price_cash':0,'price_transfer':0});else await addStock(p['id'],qty);}
}
